apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
spec:
  {{- if .Values.settings.startAsCandidate }}
  # 使用 RollingUpdate 策略时，确保至少 1 个 Pod 始终可用
  # 配合 (maxSurge: 1, maxUnavailable: 0) 策略，确保节点驱逐时
  # 新 Pod 先创建并健康运行，再终止旧 Pod
  minAvailable: 1
  {{- else }}
  # 使用 Recreate 策略时，允许 Pod 被中断
  # 因为 Recreate 策略本身不支持零停机更新
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "neon-storage-controller.selectorLabels" . | nindent 6 }}
