apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon-dummy-cp.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "neon-dummy-cp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dummy-cp
      protocol: TCP
      name: dummy-cp
  selector:
    {{- include "neon-dummy-cp.selectorLabels" . | nindent 4 }}
