# aws-cost-reporter 的默认参数值。
# 这是一个 YAML 格式的文件。
# 声明要传递到模板中的变量。

replicaCount: 1

image:
  # -- 镜像仓库地址
  repository: neondatabase/aws-cost-reporter
  # -- 镜像拉取策略
  pullPolicy: IfNotPresent
  # -- 覆盖镜像标签，默认使用 chart 的 appVersion
  tag: ""

# -- 指定 Docker 镜像仓库密钥名称数组
imagePullSecrets: []
# -- 部分覆盖 aws-cost-reporter.fullname 模板的字符串（保留发布名称）
nameOverride: ""
# -- 完全覆盖 aws-cost-reporter.fullname 模板的字符串
fullnameOverride: ""

serviceAccount:
  # -- 指定是否创建 Service Account
  create: true
  # -- 添加到 Service Account 的注解
  annotations: {}
  # -- 使用的 Service Account 名称。
  # 如果未设置且 create 为 true，则使用 fullname 模板生成名称
  name: ""
  # -- 用于访问 AWS Cost Explorer 服务的 AWS IAM Role ARN（IRSA）
  roleArn: ""

slack:
  # -- Slack App 令牌
  token: ""
  # -- Slack 频道 ID
  channelID: "#general"
  # -- Slack 消息标题
  header: "AWS Cost and Usage :moneybag:"

# -- 不使用 IRSA 时的 AWS 凭证
aws: {}
  # awsAccessKey: YOURACCESSKEY
  # awsSecretKey: YourSecretKey
  # awsRegion: eu-east-1

# -- aws-cost-reporter Pod 的注解
podAnnotations: {}

# -- aws-cost-reporter Pod 的安全上下文
podSecurityContext: {}
  # fsGroup: 2000

# -- aws-cost-reporter 容器的安全上下文
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # 通常建议不指定默认资源限制，让用户根据实际情况选择。
  # 这样也能增加 charts 在资源较少的环境（如 Minikube）中运行的可能性。
  # 如果确实需要指定资源，请取消注释以下行，根据需要调整，并删除 resources: 后的花括号。
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Pod 调度的节点标签选择器
nodeSelector: {}

# -- Pod 调度的容忍度配置
tolerations: []

# -- Pod 调度亲和性配置
affinity: {}
