apiVersion: v2
name: neon-safekeeper
description: Neon Safekeeper - WAL durability layer
type: application
version: 0.1.0
appVersion: "latest"
kubeVersion: "^1.18.x-x"
home: https://github.com/chirpyli/helm-charts
sources:
  - https://github.com/chirpyli/helm-charts
