apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neon-compute.configmapName" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "format_version": 1.0,
      "cluster": {
        "cluster_id": "k8s-deploy",
        "name": "default",
        "state": "active",
        "roles": [{
          "name": "cloud_admin",
          "encrypted_password": null,
          "login": true,
          "superuser": true
        }],
        "databases": [{
          "name": "postgres",
          "owner": "cloud_admin"
        }],
        "settings": [
          {"name": "fsync", "value": "off", "vartype": "bool"},
          {"name": "wal_level", "value": "logical", "vartype": "enum"},
          {"name": "port", "value": "{{ .Values.port }}", "vartype": "integer"},
          {"name": "shared_buffers", "value": "1MB", "vartype": "string"},
          {"name": "listen_addresses", "value": "0.0.0.0", "vartype": "string"},
          {"name": "shared_preload_libraries", "value": "neon,pg_stat_statements", "vartype": "string"},
          {"name": "neon.file_cache_path", "value": "{{ .Values.lfc.mountPath }}/file.cache", "vartype": "string"},
          {"name": "neon.max_file_cache_size", "value": "{{ .Values.lfc.maxFileCacheSizeMB }}", "vartype": "integer"}
        ]
      },
      "tenant_id": "{{ .Values.tenantId }}",
      "timeline_id": "{{ .Values.timelineId }}",
      "pageserver_connection_info": {
        "host": "{{ .Values.pageserver.host }}",
        "port": {{ .Values.pageserver.port }}
      },
      "pageserver_connstring": "host={{ .Values.pageserver.host }} port={{ .Values.pageserver.port }}",
      "safekeeper_connstrings": [
        {{- range $i, $sk := .Values.safekeepers }}
        {{- if $i}},{{ end }}"host={{ $sk.host }} port={{ $sk.port }}"
        {{- end }}
      ],
      "mode": "Primary",
      "storage_auth_token": null,
      "suspend_timeout_seconds": 3600
    }
