apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon-compute.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgsql
      protocol: TCP
      name: pgsql
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neon-compute.selectorLabels" . | nindent 4 }}
