apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon-compute.serviceName" . }}
  labels:
    {{- include "neon-compute.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pgPort }}
      targetPort: pg
      name: pg
      protocol: TCP
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http
      protocol: TCP
  selector:
    {{- include "neon-compute.selectorLabels" . | nindent 4 }}
