# neon-endpoint-storage 的默认参数值。
image:
  repository: neondatabase/neon
  pullPolicy: Always
  tag: latest
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  port: 80

skipS3Check: true
settings:
  # 如果使用 S3（测试中至少需要一个存储变体来启动服务，因此取消注释此变体）
  type: "AwsS3"
  bucket_name: ""
  bucket_region: ""
  #
  # 如果使用 Azure：
  # type: "AzureContainer"
  # container_name: ""
  # container_region: ""
  # storage_account: ""

  # 用于验证 JWT 请求的公钥，存储为包含 pemfile.pem 的 Secret。
  # 如果设置为 /certs/dummy.pem，helm chart 会使用一个虚拟的 Secret 来通过测试，
  # 否则 Secret 将挂载到此位置并传递给配置，因此可以选择任意名称
  pemfile: "/certs/dummy.pem"
  # 端口必须与 .Values.service.port 匹配
  listen: "0.0.0.0:80"

nodeSelector: {}
tolerations: []
affinity: {}

priorityClassName: ""

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 10s
    scrapeTimeout: 10s
    selector: {}
